spring:
  application:
    name: authserver
  cloud:
    config:
      # Change the profile name
      profile: local-yigit
  config:
    import: "optional:configserver:${configUrl}/"

configUrl: http://localhost:8079